# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo c:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/IO_strobe_logic.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/T_state_and_Reset.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/arithmatic.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/carry_flag_logic.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/flip.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/interrupt_capture.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/interrupt_logic.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/logical_bus_processing.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/picoblaze.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/program_counter.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/register_and_flag_enable.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/register_bank.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/memorias_programa/secded_RAM.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/memorias_programa/secded_test_32bits.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/shift_rotate.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/shift_rs232.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/stack_counter.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/stack_ram.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/picoblaze/zero_flag_logic.vhd
  C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/sources_1/imports/ficheros/toplevel.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/constrs_1/new/fichero_restricciones.xdc
set_property used_in_implementation false [get_files C:/Xilinx/TFG/secded32bits_witherrsfixed/secded32bits_witherrsfixed.srcs/constrs_1/new/fichero_restricciones.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top toplevel -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef toplevel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
